name: Update Version in Bug Report template

on:
  release:
    types:
      - published

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Release Version
        id: get_latest_release
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Update File with Version
        run: |
          echo "Latest Release: ${{ env.RELEASE_VERSION }}" > version.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version.txt with latest release"
          git checkout -b update_bug_template
          git push origin update_bug_template -f

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base main --head update_bug_template --title "Update version.txt with latest release" --body "This pull request updates version.txt with the latest release version."
